name: S3 Sync

on:
  push:
    branches:
    - main
    - develop

jobs:
  s3_sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [app, dev]
    steps:
    - uses: actions/checkout@master
    - name: Install and configure AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
    - name: Configure AWS CLI
      run: |
        if [ "${{ matrix.environment }}" == "app" ]; then
          aws configure set aws_access_key_id ${{ secrets.APP_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.APP_AWS_SECRET_ACCESS_KEY }}
        else
          aws configure set aws_access_key_id ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        fi
        aws configure set region us-east-1
    - name: Sync with S3 bucket
      run: |
        aws s3 sync . s3://janus-${{ matrix.environment }}-data-science/github/$GITHUB_REF_NAME/ --follow-symlinks --delete --exclude '.git/*'
