AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Parameters:
  Environment:
      Type: String
      AllowedValues:
        - DEV
        - PROD
      Default: DEV
  
  Version:
      Type: Number

Metadata:
  AWS::ServerlessRepo::Application:
    SemanticVersion: ${Version}

Resources:
  surelogixPROD:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: .
      Description: ''
      MemorySize: 1048
      Timeout: 900
      Handler: app.surelogix_function_temp.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          AZURE_ENDPOINT: !Sub '{{resolve:secretsmanager:DML_env_variables:SecretString:AZURE_ENDPOINT}}'
          AZURE_KEY: !Sub '{{resolve:secretsmanager:DML_env_variables:SecretString:AZURE_KEY}}'
          OPENAI_API_KEY: !Sub '{{resolve:secretsmanager:DML_env_variables:SecretString:OPENAI_API_KEY}}'
          ENVIRONMENT: !Sub 'PROD'
      Layers:
        - >-
          arn:aws:lambda:us-east-1:061008833801:layer:PortXDependencies_Python_Layer:4
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      SnapStart:
        ApplyOn: None
      PackageType: Zip
      FunctionName: !Sub 'SamTest11_PROD_surelogix'
      VersionDescription: PROD deploy
