# This is a basic workflow that is manually triggered

name: Deploy Client

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'client to deploy **exactly as it appears in the repo****case sensitive**'
        # Default value if no value is explicitly provided
        #default: 'surelogix'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      choice:
        type: choice
        required: true
        description: Environment
        options:
        - 'DEV'
        - 'PROD'
        default: 'DEV'
      

jobs:
  
  DeployClient:
    runs-on: ubuntu-latest
    environment: deploys
    strategy:
      matrix:
        python-version: [ "3.9"]
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true

    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: sam build 
      working-directory: ./lambda_functions/${{ inputs.name }}
      run: sam build --config-file ${{ inputs.choice }}.toml --template-file ${{ inputs.choice }}.yaml

    - name: create app dir
      working-directory: ./lambda_functions/${{ inputs.name }}/.aws-sam/build
      run: mkdir app

    - name: move to dir to app
      working-directory: ./lambda_functions/${{ inputs.name }}/.aws-sam/build
      run: mv ${{ inputs.name }}${{ inputs.choice }}/* app

    - name: move app to dir
      working-directory: ./lambda_functions/${{ inputs.name }}/.aws-sam/build
      run: mv app ${{ inputs.name }}${{ inputs.choice }}

    - name: list files
      working-directory: ./lambda_functions/${{ inputs.name }}/.aws-sam/build/${{ inputs.name }}${{ inputs.choice }}
      run: ls

    - name: list files
      working-directory: ./lambda_functions/${{ inputs.name }}/.aws-sam/build/${{ inputs.name }}${{ inputs.choice }}
      run: ls app
    
    # - name: sam deploy
    #   working-directory: ./lambda_functions/${{ inputs.name }}
    #   run: mytime=`date +%s`; sam deploy --config-file ${{ inputs.choice }}.toml --template-file ${{ inputs.choice }}.yaml --parameter-overrides Environment=${{ inputs.choice }} Version=$mytime


    
  
