# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'client to deploy'
        # Default value if no value is explicitly provided
        default: 'surelogix'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      choice:
        type: choice
        description: Environment
        options:
        - 'DEV'
        - 'PROD'
        default: 'DEV'
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }} ${{inputs.choice}}!}}"

  whereamI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: deploys
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: checkout repo
      uses: actions/checkout@v3

    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true

    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: sam build
      working-directory: ./lambda_functions/${{ inputs.name }}
      run: sam build

    - name: show dir
      working-directory: ./lambda_functions/${{ inputs.name }}
      run: ls
  
