name: Sync to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploys

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync with S3 bucket
      run: |
        aws s3 sync mytest/ s3://dml-data-prod/airflow_code --follow-symlinks --delete

